### ISSUE TITLE
Show Time using javascript

### ISSUE THREAD

**Issue by ibimina** [sanskarmalkhede/basic-programs#108]
Create a time/clock using javascript

**Comment by ibimina** [comment]
@sanskarmalkhede Can I work on this?

**Comment by sanskarmalkhede** [comment]
Yes please go ahead and make a PR. 
Before that make sure that you have starred the repo ⭐

**Comment by ibimina** [comment]
I haven't completed this yet??

**Comment by sanskarmalkhede** [comment]
sorry mb

**Comment by ibimina** [comment]
@sanskarmalkhede kindly help merge my pull merge
Thanks

**Comment by sanskarmalkhede** [comment]
Yeah sure!
