### ISSUE TITLE
All- imp -question-of-binarytree 

### ISSUE THREAD

**Issue by SHOBHA-0502** [sanskarmalkhede/basic-programs#139]
I want to add all the important and famous questions about binary trees which help me to crack the interview at Microsoft.

@sanskarmalkhede  kindly assign this issue to me in hactoberfest 2022.

**Comment by sanskarmalkhede** [comment]
Yes please go ahead. If you can create a new directory specially for interview it would be very nice. Like "Interview-Questions/Microsoft/Q&A_01".
But before everything make sure you have starred the repository.

**Comment by SHOBHA-0502** [comment]
sure

**Comment by SHOBHA-0502** [comment]
kindly assign this issue to me, I have not gotten the PR number.

**Comment by sanskarmalkhede** [comment]
is it ok now?

**Comment by SHOBHA-0502** [comment]
yes
