### ISSUE TITLE
Recursion Code in CPP

### ISSUE THREAD

**Issue by Atharva-77** [sanskarmalkhede/basic-programs#141]
Can I add recursion code in cpp for questions like generating all permutations of a sequence,similar variations, N-Queen? Will help other developers practising recursion.
Will add question link in comments too.

**Comment by sanskarmalkhede** [comment]
Yes please go ahead.
But before everything make sure that you have starred this repository.

**Comment by Atharva-77** [comment]
Yeah sure. Shall I directly add or make a folder of recursion inside c++ folder?

**Comment by Vaishnavi-More** [comment]
Hey @Atharva-77 !
I have some amazing problem solution on recursion topic. And I am very interested to contribute in this repository, please will you assign this issue to me!

**Comment by sanskarmalkhede** [comment]
> Yeah sure. Shall I directly add or make a folder of recursion inside c++ folder?

Yes it would be good if create a new directory add everything to avoid mess.

**Comment by Atharva-77** [comment]
Hey @Vaishnavi-More 
There are many repos online. You can contribute there. I have already started to code. Also, after my PR gets merged, you can also commit additional code in the repo.

**Comment by Vaishnavi-More** [comment]
I guess multiple people can work on same repo right?
Hey @sanskarmalkhede I am beginner and I really want to contribute so can I contribute code for different data structures. Please assign it to me.

**Comment by sanskarmalkhede** [comment]
> I guess multiple people can work on same repo right? Hey @sanskarmalkhede I am beginner and I really want to contribute so can I contribute code for different data structures. Please assign it to me.
Yes sure. Just make sure you add valuable code. But first, star this repo I'm checking star count.

**Comment by Vaishnavi-More** [comment]
Thank You @sanskarmalkhede !
Yupp I have already star your repo.

**Comment by Vaishnavi-More** [comment]
Hey @sanskarmalkhede I have requested pull request.
Kindly review and accept it!
Thank You.
