### ISSUE TITLE
Implement decimal to binary representation of number in cpp.

### ISSUE THREAD

**Issue by SardarShubham** [sanskarmalkhede/basic-programs#175]
Assign this task to me.

**Comment by sanskarmalkhede** [comment]
Task has been assigned to you. Create a PR and attach a screenshot where you  have starred the repo. to proceed further with your commits.

**Comment by SardarShubham** [comment]
thank you, can you also please attach hactoberfest label on this issue

**Comment by sanskarmalkhede** [comment]
Sure
