### ISSUE TITLE
Adding Matrix Multiplication code in C++ and of rotation of array.

### ISSUE THREAD

**Issue by KratikJain10** [sanskarmalkhede/basic-programs#180]
@sanskarmalkhede. 
hello!
Myself Kratik.
I want to add a code which multiply two matrices written in C++ and a code which rotates the array in anticlockwise direction by given shifting constant.
kindly consider and assign me to add these codes to complete my pr in hactoberfest.
Thank You.
#Hactoberfest2022

**Comment by sanskarmalkhede** [comment]
I have assigned you this issue. Now go ahead and create a PR. Also don't forget to add the screenshot of you starred this repository.

**Comment by KratikJain10** [comment]
@sanskarmalkhede this repository is been excluded from hactoberfest,,kindly update it in your readme.

**Comment by sanskarmalkhede** [comment]
yeah sure. I just came to know. Thanks for reminding.
