### ISSUE TITLE
Adding 2 player ping pong game in python

### ISSUE THREAD

**Issue by rajdeepdas2000** [sanskarmalkhede/basic-programs#182]
I have added ping pong game in python folder. Kindly assign me. Thanks.

**Comment by sanskarmalkhede** [comment]
I have assigned you this issue. Now go ahead and create a PR. Also don't forget to add the screenshot of you starred this repository.

**Comment by rajdeepdas2000** [comment]
i have raised pr #183 . where shall I add screenshot of starred repository?

**Comment by sanskarmalkhede** [comment]
I will merge.
