### ISSUE TITLE
Snake Water gun game in python 

### ISSUE THREAD

**Issue by anishaxtha** [sanskarmalkhede/basic-programs#61]
Snake water gun game is a game that requires two players both have to select something from a snake or water or gun
Here, the snake wins over water by drinking water, the gun win over the snake by killing the snake, and water wins over the gun when the gun is drowned in water. ultimately the player with the maximum points wins the game.
 
the code includes the random modules  of the python 

Please assign this issue to me with hacktoberfest label :)

**Comment by sanskarmalkhede** [comment]
Yes please go ahead and make a PR. Really looking forward to your contribution.
Make sure that you have starred the repo.
