### ISSUE TITLE
Segment Tree Implementation for the C++ module  [proposed Label] hacktober-fest

### ISSUE THREAD

**Issue by xynister9** [sanskarmalkhede/basic-programs#63]
Would like to add implementation of segment tree in C++ , planning on adding more data structures like DSU , Fenwish tree etc . Please assign me this issue

**Comment by sanskarmalkhede** [comment]
Yes Please go ahead.

**Comment by xynister9** [comment]
@sanskarmalkhede

**Comment by sanskarmalkhede** [comment]
Make sure you have starred the repo ⭐

**Comment by xynister9** [comment]
Yeah I have started the repo please see the pr @sanskarmalkhede
