### ISSUE TITLE
Longest Palindromic Subsequence

### ISSUE THREAD

**Issue by vinayassrao** [sanskarmalkhede/basic-programs#7]
Given a String, find the longest palindromic subsequence.

I would like to contribute to this problem . Please assign me this

**Comment by sanskarmalkhede** [comment]
Of course you can contribute, looking forward for your PR.

**Comment by sanskarmalkhede** [comment]
Hey you can upload your code now.

**Comment by vinayassrao** [comment]
Sorry for the delay
