### ISSUE TITLE
Adding code for Rust language

### ISSUE THREAD

**Issue by GAURCODER** [sanskarmalkhede/basic-programs#74]
As the name suggest can i add Code written in rust language.

**Comment by GAURCODER** [comment]
@sanskarmalkhede  can you assign me this issue?

**Comment by sanskarmalkhede** [comment]
will you create a RUST named folder or I have to create? because there is no rust folder in this repo.

**Comment by GAURCODER** [comment]
I will do it

**Comment by sanskarmalkhede** [comment]
Ok then go ahead and make a PR.
